import { siteUrl } from "@/lib/site";

export const SITE_NAME = "RealTimeBillionaire";

/**
 * Shared publisher entity for every Article/NewsArticle JSON-LD block.
 * Google requires a publisher logo (raster, <=600px wide) for article
 * rich results — /logo.png is generated by app/logo.png/route.tsx.
 */
export function publisherJsonLd() {
  return {
    "@type": "NewsMediaOrganization",
    name: SITE_NAME,
    url: siteUrl(),
    logo: {
      "@type": "ImageObject",
      url: `${siteUrl()}/logo.png`,
      width: 600,
      height: 60,
    },
  };
}

/** The dynamically-generated share card for a person — used as schema image. */
export function personImageUrl(personId: string): string {
  return `${siteUrl()}/billionaire/${personId}/opengraph-image`;
}

/** Turn a headline into a full-title URL slug (ET-style). */
export function slugifyTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/%/g, " percent")
    .replace(/\$/g, "")
    .replace(/&/g, " and ")
    .replace(/['’.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
